### PR TITLE
FIX for issue #4: Allow newer versions of SilverStripe (>= 3.1x and <4.0.x)

### PR DESCRIPTION
**Pull request by patricknelson**
Tested this in `v3.3` and still working fine. Here's the updated code! 

p.s. Let me know if you need someone to help maintain this for you as well.

### CODE REVIEW

**Comment by richardsjoqvist** [comment]
Thanks! If you would like to help maintain/develop this (and possibly any of my other SS modules) that sure would be a big help as my time is limited to say the least right now.

**Comment by patricknelson** [comment]
Ok cool, thank you @richardsjoqvist! This one is simple enough that it'd be easy to maintain (since I already use it). I forked it and submitted my own packagist entry (just with my own name prefixed) just in case, your github was abandoned but it looks like you're still around and well :joy: I'll have to undo all that, hah (overly ambitious)

**Comment by patricknelson** [comment]
Actually @richardsjoqvist it looks like this isn't yet updated in packagist -- see here: https://packagist.org/packages/richardsjoqvist/silverstripe-optionaltreedropdownfield

I tried installing again via `composer` and it still failed since it's still stuck on the `3.1.*` requirement as far as they know.

**Comment by richardsjoqvist** [comment]
Sorry I forgot to create a tag! Fixed now.

**Pull request merged**
